language: java
# how to install and set jdk on travis:
# - Testing Against Multiple JDKs
#   https://docs.travis-ci.com/user/languages/java/#Testing-Against-Multiple-JDKs
# - JVM images
#   https://docs.travis-ci.com/user/reference/trusty/#JVM-(Clojure%2C-Groovy%2C-Java%2C-Scala)-images
# - Customizing the Build / Build Matrix
#   https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix

addons:
  apt:
    packages:
      - openjdk-6-jdk

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk8
  - oraclejdk9

before_install:
  # workaroud for "buffer overflow detected" problem of openjdk:
  #     https://github.com/travis-ci/travis-ci/issues/5227
  # borrow from https://github.com/miguno/kafka-storm-starter/blob/01dd534263eb867304c06cd2a72f640da1bd9367/.travis.yml
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts > /tmp/hosts
  - sudo mv /tmp/hosts /etc/hosts
  - cat /etc/hosts # optionally check the content *after*

  # output env info
  - uname -a
  - ls /usr/lib/jvm/*
  - find /usr/lib/jvm/java-6-openjdk-amd64 -type f
  - echo -e "JAVA_HOME=$JAVA_HOME\nPATH=$PATH"
  - ./mvnw --version

  - pip install --user codecov

script:
  - ./mvnw clean install --batch-mode
  - ./run-agent-test.sh skip

after_success:
  - codecov

# cache between builds
cache:
  directories:
    - $HOME/.m2
    - $HOME/.cache/pip
